### ISSUE TITLE
Cucumber tags

### ISSUE THREAD

**Issue by Noctua36** [cucumber/cucumber-electron#12]
Hi, it's possible to pass tags to cucumber-js command? I wan't to skip the features with @wip tag when using cucumber-electron. With cucumber-js it's enough to run 
`cucumber-js --tags ~@wip`
but 
`cucumber-electron --tags ~@wip`
gives me the error 

> error: unknown option `--tags'

**Comment by joshski** [comment]
Hi @Noctua36,

Thanks for pointing this out! Fixed and released in v2.3.0.

**Comment by aslakhellesoy** [comment]
@Noctua36 beware that the tag syntax has changed:

https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#200-rc0-2016-11-25
https://docs.cucumber.io/tag-expressions/

**Comment by Noctua36** [comment]
oh, thanks for the heads up @aslakhellesoy
