### ISSUE TITLE
Puppeteer?

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-electron#14]
Would it be possible to use https://github.com/GoogleChrome/puppeteer as an alternative to Chrome?

Pros/cons @joshski?

**Comment by joshski** [comment]
It would be a viable alternative to electron (not chrome), but it has a very different API and it looks as though it wouldn't have any of the benefits of this project, which is to run a single process with both node and DOM code in it.

Puppeteer looks like much more of a selenium equivalent, only targeting one specific browser, with some low-level capabilities that are missing from selenium.
