### ISSUE TITLE
3rd party lib's debug messages always printed 

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-electron#43]
I've got a repo that depends on both `express` and `@cucumber/electron`. The `debug` log statements from express are always printed, even though I haven't defined the `DEBUG` env var.

I suspect this is due to something going on inside `@cucumber/electron`.

Any idea @joshski ?

**Comment by jbpros** [comment]
Is this still an issue or should I close for now?

If it is, could you share some code to reproduce?
