### ISSUE TITLE
Better getting started

### ISSUE THREAD

**Issue by ambroiseRabier** [cucumber/cucumber-electron#58]
Hello, I am struggling to understand how to get started with cucumber-electron.

In the podcast here: https://cucumber.io/blog/podcast/cucumber-electron/ ,  you say you use https://github.com/featurist/browser-monkey .

From https://cucumber.io/blog/open-source/announcing-cucumber-electron/ :

> This approach is a compelling alternative to using a frameworks like Selenium WebDriver, which automate real browsers like Chrome and Firefox, or even tools like PhantomJS which automate a headless virtual browser. Because there is only one process, scenarios run much faster and debugging failures is significantly simpler. 

We learn that it is a tool comparable to selenium, but that is faster and easier to debug.

I did not see comparison with puppeteer.

Is there any example project using cucumber-electron ?

How do you setup your project ? Do you re-use electron main and renderer entry-point file ?

Does using IPC still work ?

Does it work with typescript, does it need additional config ?

Is `browser-monkey` the same as using puppeteer API or `@testing-library/user-event` ? Are both good to use with cucumber-electron ?

How does that integrate with webpack ? (I am using https://www.electronforge.io/templates/typescript-+-webpack-template)

I used cucumber previously with puppeteer on a react web app. Cucumber with puppeteer was a separated process, and I just started my react app in dev mode to do my tests.

Sorry for so many questions, it seem like an interesting tool, an alternative to spectron or puppeteer. I am just very confused on how to integrate it. It could also benefit the package popularity.

**Comment by aslakhellesoy** [comment]
Thanks for nudging us to do this @ambroiseRabier! I think the best way to showcase Cucumber-Electron is a little example project in a different repo.

I think it should showcase:

* How to run blazing fast tests (100 per second) against the UI without needing a server
  * Techniques for decoupling the UI from the HTTP layer
* How to interact with the UI
  * Using [Testing Library](https://testing-library.com/) to *insteract* with the UI
  * Using [microdata](https://github.com/cucumber/microdata/) to make assertions against the UI
