### ISSUE TITLE
Fixed electron version

### ISSUE THREAD

**Issue by Noctua36** [cucumber/cucumber-electron#8]
Hi. Any special reason to keep the electron version fixed on "1.4.15"? I have some native modules that need to be compiled against the electron version and this is causing "Module mismatch errors" when I try to run my features. I fixed my problem by changing the electron version of cucumber-electron in a npm-shrinkwrap.json file:
```json
{
  "name": "delibera",
  "version": "1.0.0",
  "dependencies": {
    "cucumber-electron": {
      "version": "2.1.4",
      "from": "cucumber-electron@>=2.1.4 <3.0.0",
      "resolved": "https://registry.npmjs.org/cucumber-electron/-/cucumber-electron-2.1.4.tgz",
      "dev": true,
      "dependencies": {
        "electron": {
          "version": "1.6.2",
          "from": "electron@>=1.6.0 <2.0.0",
          "resolved": "https://registry.npmjs.org/electron/-/electron-1.6.2.tgz",
          "dev": true
        }
      }
    }
  }
}
 ```
Do you know if there's  some incompatibility with the latest version of electron?

**Comment by joshski** [comment]
Hi @Noctua36 - no special reason. I've been meaning to remove the electron dependency altogether for the reason you mention. If you want to make a PR go ahead, otherwise I'll do it soon.
