### ISSUE TITLE
Where to I insert the main.js or where does the app open the browser for the local application?

### ISSUE THREAD

**Issue by arosado2895** [cucumber/cucumber-electron#83]
I have a local electron desktop app. I'm a bit confused on this repos configuration as to where exactly is it telling the application to open or run.

**Comment by jkronegg** [comment]
It's not really an issue (a bug) but more a question. You should ask it on the Slack channel or on Stackoverflow.  https://cucumber.io/docs/community/get-in-touch/

**Comment by jkronegg** [comment]
Should be asked on https://cucumber.io/docs/community/get-in-touch/
